services:
  todo-app:
    image: node:24
    container_name: todo-app
    volumes:
      - ./app:/app
    working_dir: /app
    # Docker / skrypt chce wiedzieć: jaki UID/GID użyć dla użytkownika w kontenerze, żeby pasował do katalogów hosta.
    user: "${USER_ID}:${GROUP_ID}"
    tty: true
    ports:
      - "3000:3000"